# -*- coding: utf-8 -*-

### SIGNAL IN SDK ###

# RECEIVE SIGNAL
RECV_SERVER_HINT = 0
RECV_TXT_MSG = 1
RECV_PIC_MSG = 3
RECV_GZH_MSG = 5
RECV_SNS_MSG = 9
RECV_HISTORY_MSG = 19
RECV_APP_MSG = 33
RECV_FRIEND_REQUEST = 37
RECV_STICKER_MSG = 47
RECV_XML_MSG = 49  # TXT_CITE, FILE
RECV_DVC_MSG = 51  # Type from DVC below this section
RECV_VIDEO_MSG = 52
RECV_MUSIC_MSG = 53
RECV_CITE_MSG = 57
RECV_APPAUDIO_MSG = 92

RECV_HOOK_SNS = 50
RECV_OTHER_MSG = 10002  # REVOKE, PAT,

# By other device type 51
OP_READ_MSG_WHILE_OPEN_DVC = RECV_OTHER_MSG + 1
OP_OPEN_CHAT_DVC = RECV_OTHER_MSG + 2
OP_REFRESH_LIST_DVC = RECV_OTHER_MSG + 4  # sync user list ?
OP_SNS_CHECK_UNREAD_DVC = RECV_OTHER_MSG + 7  #
OP_SNS_SELF_ACTION_DVC = RECV_OTHER_MSG + 9  # CHECK_SNS_UPDATE, DELETE MSG
OP_REFRESH_MSG_DVC = RECV_OTHER_MSG + 11  # HandOff with server, always when refresh
OP_DELETE_CHATROOM_MSG_DVC = RECV_OTHER_MSG + 16  # Delete all messages in 1 chat

# SEND SIGNAL
ADD_MEMBER_CHATROOM = 100
DEL_MEMBER_CHATROOM = 101
INVITE_MEMBER_CHATROOM = 102
MODIFY_SELF_NAME = 105
CREATE_CHATROOM = 120
QUIT_CHATROOM = 121
ADD_TOP_MSG = 125
DEL_TOP_MSG = 126
SEND_PIC_MSG = 500
SEND_TXT_MSG = 550
SEND_FORWARD_MSG = 551
SEND_FORWARD_GZH_MSG = 552
SEND_FORWARD_GZH_ID_MSG = 553
SEND_TXT_AT_MSG = 555
SEND_PAT_MSG = 556
SEND_APPLET_MSG = 560
SEND_ATTACH_FILE = 570
SEND_CUSTOM_EMJ = 580
DECODE_IMG_FILE = 690
OCR_IMG_FILE = 691
DW_ATTACH_FILE = 696
DW_VOICE_FILE = 697
ADD_MSG_FAVOUR = 1000
ADD_IMG_FAVOUR = 1001
GET_SNS_FIRST = 1500
GET_SNS_NEXT = 1501
GET_USER_LIST = 5000
GET_CHATROOM_INFO = 5050
GET_CHATROOM_MEMBER = 5010
CHECK_LOGIN = 6500
CHECK_SELF_INFO = 6501
CHECK_DB_INFO = 6502
CHECK_PERSON_INFO = 6550
EXEC_SQL = 7500
ENABLE_WECHAT_LOG = 10098
DISABLE_WECHAT_LOG = 10099
